export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';
export const UPDATE_POST_LIST = 'UPDATE_POST_LIST';
export const UPDATE_POST_COMMENTS = 'UPDATE_POST_COMMENTS';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';